language: generic
sudo: required
services: 
  - docker
before_install:
  - docker build -t rajatchauhan407/cal-up -f Dockerfile.dev .
script:
  - docker run -e CI=true rajatchauhan407/react-docker npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "calup"
  env: "Calup-env"
  bucket_name: "elasticbeanstalk-us-east-1-745411510829"
  bucket_path: "calup"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"