language: generic
sudo: required
services: 
  - docker
before_install:
  - docker build -t rajatchauhan407/calup-frontend -f Dockerfile .
# script:
#   - docker run -e CI=true rajatchauhan407/cal-up npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "calup-frontend"
  env: "Calupfrontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-745411510829"
  bucket_path: "calup-frontend"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"